import "bootstrap/dist/css/bootstrap.css";
import BootstrapClient from "./componets/BootstrapClient";
import { ReactQueryProvider } from "./react-query-provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  icons:{
    icon: '/imgs/OAA_Logos/crop_logo.JPG'
  }
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
        <BootstrapClient />
        <ToastContainer />
      </body>
    </html>
  );
}
